-- Schéma initial ODC Academy. IF NOT EXISTS : sans effet sur une base créée auparavant par Hibernate (ddl-auto=update).
CREATE TABLE IF NOT EXISTS users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         varchar(255) NOT NULL,
    prenom      varchar(255) NOT NULL,
    email       varchar(255) NOT NULL UNIQUE,
    password    varchar(255) NOT NULL,
    role        varchar(255) NOT NULL,
    active      boolean      NOT NULL,
    created_at  timestamp(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) NOT NULL UNIQUE,
    description varchar(500),
    active      boolean      NOT NULL
);

CREATE TABLE IF NOT EXISTS formations (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(255) NOT NULL,
    description varchar(4000),
    active      boolean      NOT NULL
);

CREATE TABLE IF NOT EXISTS formation_trainers (
    formation_id bigint NOT NULL REFERENCES formations (id),
    user_id      bigint NOT NULL REFERENCES users (id),
    PRIMARY KEY (formation_id, user_id)
);

CREATE TABLE IF NOT EXISTS courses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        varchar(255) NOT NULL,
    description  varchar(2000),
    level        varchar(255) NOT NULL,
    price        double precision NOT NULL,
    formation_id bigint REFERENCES formations (id),
    active       boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS modules (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(255) NOT NULL,
    description varchar(1000),
    order_index integer NOT NULL,
    course_id   bigint  NOT NULL REFERENCES courses (id)
);

CREATE TABLE IF NOT EXISTS lessons (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            varchar(255) NOT NULL,
    content          varchar(2000),
    course_id        bigint  NOT NULL REFERENCES courses (id),
    module_id        bigint  REFERENCES modules (id),
    video_url        varchar(255),
    document_url     varchar(255),
    duration_minutes integer,
    order_index      integer NOT NULL
);

CREATE TABLE IF NOT EXISTS quizzes (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         varchar(255) NOT NULL,
    description   varchar(1000),
    passing_score integer NOT NULL,
    active        boolean NOT NULL,
    lesson_id     bigint  NOT NULL UNIQUE REFERENCES lessons (id)
);

CREATE TABLE IF NOT EXISTS questions (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt  varchar(255) NOT NULL,
    type    varchar(255) NOT NULL,
    quiz_id bigint       NOT NULL REFERENCES quizzes (id)
);

CREATE TABLE IF NOT EXISTS answer_options (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label       varchar(255) NOT NULL,
    correct     boolean      NOT NULL,
    question_id bigint       NOT NULL REFERENCES questions (id)
);

CREATE TABLE IF NOT EXISTS quiz_attempts (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint  NOT NULL REFERENCES users (id),
    quiz_id      bigint  NOT NULL REFERENCES quizzes (id),
    score        integer NOT NULL,
    passed       boolean NOT NULL,
    attempted_at timestamp(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS enrollments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL REFERENCES users (id),
    course_id   bigint NOT NULL REFERENCES courses (id),
    status      varchar(255) NOT NULL,
    enrolled_at timestamp(6) NOT NULL,
    UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS progress (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint  NOT NULL REFERENCES users (id),
    course_id         bigint  NOT NULL REFERENCES courses (id),
    completed_lessons integer NOT NULL,
    total_lessons     integer NOT NULL,
    percentage        double precision NOT NULL,
    status            varchar(255) NOT NULL,
    updated_at        timestamp(6) NOT NULL,
    UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS lesson_completions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint NOT NULL REFERENCES users (id),
    lesson_id    bigint NOT NULL REFERENCES lessons (id),
    completed_at timestamp(6) NOT NULL,
    UNIQUE (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS assignments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(255) NOT NULL,
    description varchar(2000),
    course_id   bigint NOT NULL REFERENCES courses (id),
    opens_at    timestamp(6) NOT NULL,
    closes_at   timestamp(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS submissions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id bigint NOT NULL REFERENCES assignments (id),
    learner_id    bigint NOT NULL REFERENCES users (id),
    file_key      varchar(255) NOT NULL,
    original_name varchar(255),
    submitted_at  timestamp(6) NOT NULL,
    grade         double precision,
    feedback      varchar(2000),
    UNIQUE (assignment_id, learner_id)
);

CREATE TABLE IF NOT EXISTS forum_posts (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    formation_id bigint NOT NULL REFERENCES formations (id),
    author_id    bigint NOT NULL REFERENCES users (id),
    parent_id    bigint REFERENCES forum_posts (id),
    title        varchar(255),
    body         varchar(4000) NOT NULL,
    created_at   timestamp(6)  NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id    bigint NOT NULL REFERENCES users (id),
    recipient_id bigint NOT NULL REFERENCES users (id),
    subject      varchar(255)  NOT NULL,
    body         varchar(4000) NOT NULL,
    sent_at      timestamp(6)  NOT NULL,
    read_at      timestamp(6)
);

-- Index sur les clés étrangères les plus sollicitées
CREATE INDEX IF NOT EXISTS idx_courses_formation   ON courses (formation_id);
CREATE INDEX IF NOT EXISTS idx_lessons_course      ON lessons (course_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_user    ON enrollments (user_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_course  ON enrollments (course_id);
CREATE INDEX IF NOT EXISTS idx_progress_user       ON progress (user_id);
CREATE INDEX IF NOT EXISTS idx_assignments_course  ON assignments (course_id);
CREATE INDEX IF NOT EXISTS idx_forum_formation     ON forum_posts (formation_id, parent_id);
CREATE INDEX IF NOT EXISTS idx_messages_recipient  ON messages (recipient_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_sender     ON messages (sender_id, sent_at DESC);
