-- Colonnes ajoutées après la première version (idempotent : sûr sur base neuve comme sur base existante)
ALTER TABLE users      ADD COLUMN IF NOT EXISTS photo_key  varchar(255);
ALTER TABLE users      ADD COLUMN IF NOT EXISTS google_sub varchar(255);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image_key  varchar(255);
ALTER TABLE formations ADD COLUMN IF NOT EXISTS image_key  varchar(255);
ALTER TABLE formations ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES categories (id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_google_sub') THEN
        ALTER TABLE users ADD CONSTRAINT uq_users_google_sub UNIQUE (google_sub);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash varchar(64)  NOT NULL UNIQUE,
    expires_at timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reset_user    ON password_reset_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_reset_expires ON password_reset_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_formations_category ON formations (category_id);
