ALTER TABLE courses
    ADD COLUMN created_at timestamp(6),
    ADD COLUMN created_by_id bigint REFERENCES users (id);

CREATE TABLE live_sessions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id    bigint NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    created_by_id bigint NOT NULL REFERENCES users (id),
    title        varchar(255) NOT NULL,
    room_name    varchar(80) NOT NULL UNIQUE,
    scheduled_at timestamp(6) NOT NULL,
    status       varchar(20) NOT NULL DEFAULT 'PLANIFIE',
    started_at   timestamp(6),
    ended_at     timestamp(6),
    created_at   timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_live_sessions_status CHECK (status IN ('PLANIFIE', 'PREPARATION', 'EN_COURS', 'TERMINE'))
);
CREATE INDEX idx_live_sessions_course_schedule ON live_sessions (course_id, scheduled_at);
