CREATE TABLE course_sessions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id  bigint NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    name       varchar(120) NOT NULL,
    starts_at  timestamp(6) NOT NULL,
    ends_at    timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL
);

ALTER TABLE enrollments
    ADD COLUMN session_id bigint REFERENCES course_sessions (id) ON DELETE SET NULL;

DO $$
DECLARE
    constraint_name text;
BEGIN
    FOR constraint_name IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'enrollments'::regclass
          AND contype = 'u'
          AND pg_get_constraintdef(oid) LIKE 'UNIQUE (user_id, course_id)%'
    LOOP
        EXECUTE format('ALTER TABLE enrollments DROP CONSTRAINT %I', constraint_name);
    END LOOP;
END $$;

CREATE UNIQUE INDEX uq_enrollments_user_session
    ON enrollments (user_id, session_id)
    WHERE session_id IS NOT NULL;
CREATE INDEX idx_course_sessions_course_dates
    ON course_sessions (course_id, starts_at, ends_at);
CREATE INDEX idx_enrollments_session
    ON enrollments (session_id);
